ci:
    autofix_prs: false
repos:
-   repo: https://github.com/mwouts/jupytext
    rev: v1.14.0  # CURRENT_TAG/COMMIT_HASH
    hooks:
    - id: jupytext
      args: [--sync, --pipe, black]
      additional_dependencies:
        - black==22.3.0
        - flake8==3.9.2
        - isort==5.9.3
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: debug-statements
    -   id: end-of-file-fixer
        exclude: \.txt$
    -   id: trailing-whitespace
# TODO
# -   repo: https://github.com/nbQA-dev/nbQA
#     rev: 1.6.3
#     hooks:
#     - id: nbqa-isort
#         args: [--profile, black]
#     - id: nbqa-flake8
#         args: [--ignore=E402]
-   repo: https://github.com/PyCQA/isort
    rev: 5.9.3
    hooks:
    -   id: isort
        args: ["--profile", "black"]
-   repo: https://github.com/python/black
    rev: 22.3.0
    hooks:
    -   id: black
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
        args: [--per-file-ignores=__init__.py:F401]
        additional_dependencies: &flake8_dependencies
        - flake8==3.9.2
        - flake8-comprehensions==3.1.0
        - flake8-bugbear==21.3.2
        - flake8-print==4.0.0
